sleep = 1
host = '0.0.0.0'
port = 9999
log_name = 'hubernetes.log'
log_format = u'%(filename)s[LINE:%(lineno)d]# %(levelname)-8s [%(asctime)s]  %(message)s'
log_level = 30
etcd_host='127.0.0.1'
etcd_port=2379
etcd_dir='/hubernetes'
debug = True
